# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yis_sdk/instruction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yis_sdk/instruction.proto',
  package='yis_sdk',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19yis_sdk/instruction.proto\x12\x07yis_sdk\"$\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05width\x18\x02 \x02(\x05\"A\n\x11InstructionFormat\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1e\n\x06\x66ields\x18\x02 \x03(\x0b\x32\x0e.yis_sdk.Field\"\xd3\x02\n\x14\x41llInstructionFormat\x12\x37\n\x13instruction_formats\x18\x01 \x03(\x0b\x32\x1a.yis_sdk.InstructionFormat\x12L\n\x11instr_op_code_map\x18\x02 \x03(\x0b\x32\x31.yis_sdk.AllInstructionFormat.InstrOpCodeMapEntry\x12H\n\x0f\x61lu_op_code_map\x18\x03 \x03(\x0b\x32/.yis_sdk.AllInstructionFormat.AluOpCodeMapEntry\x1a\x35\n\x13InstrOpCodeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x33\n\x11\x41luOpCodeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01')
)




_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='yis_sdk.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yis_sdk.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='yis_sdk.Field.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=74,
)


_INSTRUCTIONFORMAT = _descriptor.Descriptor(
  name='InstructionFormat',
  full_name='yis_sdk.InstructionFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yis_sdk.InstructionFormat.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='yis_sdk.InstructionFormat.fields', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=141,
)


_ALLINSTRUCTIONFORMAT_INSTROPCODEMAPENTRY = _descriptor.Descriptor(
  name='InstrOpCodeMapEntry',
  full_name='yis_sdk.AllInstructionFormat.InstrOpCodeMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yis_sdk.AllInstructionFormat.InstrOpCodeMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='yis_sdk.AllInstructionFormat.InstrOpCodeMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=430,
)

_ALLINSTRUCTIONFORMAT_ALUOPCODEMAPENTRY = _descriptor.Descriptor(
  name='AluOpCodeMapEntry',
  full_name='yis_sdk.AllInstructionFormat.AluOpCodeMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='yis_sdk.AllInstructionFormat.AluOpCodeMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='yis_sdk.AllInstructionFormat.AluOpCodeMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=483,
)

_ALLINSTRUCTIONFORMAT = _descriptor.Descriptor(
  name='AllInstructionFormat',
  full_name='yis_sdk.AllInstructionFormat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instruction_formats', full_name='yis_sdk.AllInstructionFormat.instruction_formats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instr_op_code_map', full_name='yis_sdk.AllInstructionFormat.instr_op_code_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alu_op_code_map', full_name='yis_sdk.AllInstructionFormat.alu_op_code_map', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ALLINSTRUCTIONFORMAT_INSTROPCODEMAPENTRY, _ALLINSTRUCTIONFORMAT_ALUOPCODEMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=483,
)

_INSTRUCTIONFORMAT.fields_by_name['fields'].message_type = _FIELD
_ALLINSTRUCTIONFORMAT_INSTROPCODEMAPENTRY.containing_type = _ALLINSTRUCTIONFORMAT
_ALLINSTRUCTIONFORMAT_ALUOPCODEMAPENTRY.containing_type = _ALLINSTRUCTIONFORMAT
_ALLINSTRUCTIONFORMAT.fields_by_name['instruction_formats'].message_type = _INSTRUCTIONFORMAT
_ALLINSTRUCTIONFORMAT.fields_by_name['instr_op_code_map'].message_type = _ALLINSTRUCTIONFORMAT_INSTROPCODEMAPENTRY
_ALLINSTRUCTIONFORMAT.fields_by_name['alu_op_code_map'].message_type = _ALLINSTRUCTIONFORMAT_ALUOPCODEMAPENTRY
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['InstructionFormat'] = _INSTRUCTIONFORMAT
DESCRIPTOR.message_types_by_name['AllInstructionFormat'] = _ALLINSTRUCTIONFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), {
  'DESCRIPTOR' : _FIELD,
  '__module__' : 'yis_sdk.instruction_pb2'
  # @@protoc_insertion_point(class_scope:yis_sdk.Field)
  })
_sym_db.RegisterMessage(Field)

InstructionFormat = _reflection.GeneratedProtocolMessageType('InstructionFormat', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONFORMAT,
  '__module__' : 'yis_sdk.instruction_pb2'
  # @@protoc_insertion_point(class_scope:yis_sdk.InstructionFormat)
  })
_sym_db.RegisterMessage(InstructionFormat)

AllInstructionFormat = _reflection.GeneratedProtocolMessageType('AllInstructionFormat', (_message.Message,), {

  'InstrOpCodeMapEntry' : _reflection.GeneratedProtocolMessageType('InstrOpCodeMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _ALLINSTRUCTIONFORMAT_INSTROPCODEMAPENTRY,
    '__module__' : 'yis_sdk.instruction_pb2'
    # @@protoc_insertion_point(class_scope:yis_sdk.AllInstructionFormat.InstrOpCodeMapEntry)
    })
  ,

  'AluOpCodeMapEntry' : _reflection.GeneratedProtocolMessageType('AluOpCodeMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _ALLINSTRUCTIONFORMAT_ALUOPCODEMAPENTRY,
    '__module__' : 'yis_sdk.instruction_pb2'
    # @@protoc_insertion_point(class_scope:yis_sdk.AllInstructionFormat.AluOpCodeMapEntry)
    })
  ,
  'DESCRIPTOR' : _ALLINSTRUCTIONFORMAT,
  '__module__' : 'yis_sdk.instruction_pb2'
  # @@protoc_insertion_point(class_scope:yis_sdk.AllInstructionFormat)
  })
_sym_db.RegisterMessage(AllInstructionFormat)
_sym_db.RegisterMessage(AllInstructionFormat.InstrOpCodeMapEntry)
_sym_db.RegisterMessage(AllInstructionFormat.AluOpCodeMapEntry)


_ALLINSTRUCTIONFORMAT_INSTROPCODEMAPENTRY._options = None
_ALLINSTRUCTIONFORMAT_ALUOPCODEMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
