# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk2/proto/calibration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sdk2.proto import lgf_pb2 as sdk2_dot_proto_dot_lgf__pb2
from sdk2.proto import common_pb2 as sdk2_dot_proto_dot_common__pb2
from sdk2.proto import dtypes_pb2 as sdk2_dot_proto_dot_dtypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sdk2/proto/calibration.proto',
  package='light',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1csdk2/proto/calibration.proto\x12\x05light\x1a\x14sdk2/proto/lgf.proto\x1a\x17sdk2/proto/common.proto\x1a\x17sdk2/proto/dtypes.proto\"x\n\x14\x43\x61librationHistogram\x12\x0c\n\x04hist\x18\x01 \x03(\x05\x12\r\n\x05value\x18\x04 \x03(\x02\"C\n\tValueType\x12\x11\n\rHISTOGRAM_MAX\x10\x00\x12\r\n\tNUM_ZEROS\x10\x01\x12\x14\n\x10\x44ISTRIBUTION_MAX\x10\x02\"(\n\tScaleInfo\x12\r\n\x05scale\x18\x01 \x01(\x02\x12\x0c\n\x04\x62ias\x18\x02 \x01(\x02\",\n\rScaleInfoList\x12\x1b\n\x01l\x18\x01 \x03(\x0b\x32\x10.light.ScaleInfo\"6\n\x08NodeInfo\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x17\n\x0fquant_precision\x18\x02 \x01(\x05\"\x9c\x01\n\rNodeScalePair\x12\"\n\tnode_info\x18\x01 \x01(\x0b\x32\x0f.light.NodeInfo\x12&\n\nscale_info\x18\x02 \x01(\x0b\x32\x10.light.ScaleInfoH\x00\x12/\n\x0fscale_info_list\x18\x03 \x01(\x0b\x32\x14.light.ScaleInfoListH\x00\x42\x0e\n\x0cscale_option\"5\n\x0fQuantScalesData\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.light.NodeScalePair\"r\n\tSimpleMap\x12\x33\n\nsimple_map\x18\x01 \x03(\x0b\x32\x1f.light.SimpleMap.SimpleMapEntry\x1a\x30\n\x0eSimpleMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x94\x01\n\x0cScaleInfoMap\x12=\n\x0escale_info_map\x18\x01 \x03(\x0b\x32%.light.ScaleInfoMap.ScaleInfoMapEntry\x1a\x45\n\x11ScaleInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.light.ScaleInfo:\x02\x38\x01*X\n\rHistogramMode\x12\x0e\n\nHM_INVALID\x10\x00\x12\x11\n\rHM_UPDATE_MAX\x10\x01\x12\x14\n\x10HM_POPULATE_HIST\x10\x02\x12\x0e\n\nHM_PADDING\x10\x03\x62\x06proto3')
  ,
  dependencies=[sdk2_dot_proto_dot_lgf__pb2.DESCRIPTOR,sdk2_dot_proto_dot_common__pb2.DESCRIPTOR,sdk2_dot_proto_dot_dtypes__pb2.DESCRIPTOR,])

_HISTOGRAMMODE = _descriptor.EnumDescriptor(
  name='HistogramMode',
  full_name='light.HistogramMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HM_INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HM_UPDATE_MAX', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HM_POPULATE_HIST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HM_PADDING', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=858,
  serialized_end=946,
)
_sym_db.RegisterEnumDescriptor(_HISTOGRAMMODE)

HistogramMode = enum_type_wrapper.EnumTypeWrapper(_HISTOGRAMMODE)
HM_INVALID = 0
HM_UPDATE_MAX = 1
HM_POPULATE_HIST = 2
HM_PADDING = 3


_CALIBRATIONHISTOGRAM_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='light.CalibrationHistogram.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HISTOGRAM_MAX', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUM_ZEROS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRIBUTION_MAX', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=164,
  serialized_end=231,
)
_sym_db.RegisterEnumDescriptor(_CALIBRATIONHISTOGRAM_VALUETYPE)


_CALIBRATIONHISTOGRAM = _descriptor.Descriptor(
  name='CalibrationHistogram',
  full_name='light.CalibrationHistogram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hist', full_name='light.CalibrationHistogram.hist', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='light.CalibrationHistogram.value', index=1,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CALIBRATIONHISTOGRAM_VALUETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=231,
)


_SCALEINFO = _descriptor.Descriptor(
  name='ScaleInfo',
  full_name='light.ScaleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale', full_name='light.ScaleInfo.scale', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bias', full_name='light.ScaleInfo.bias', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=273,
)


_SCALEINFOLIST = _descriptor.Descriptor(
  name='ScaleInfoList',
  full_name='light.ScaleInfoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='l', full_name='light.ScaleInfoList.l', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=319,
)


_NODEINFO = _descriptor.Descriptor(
  name='NodeInfo',
  full_name='light.NodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_name', full_name='light.NodeInfo.node_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quant_precision', full_name='light.NodeInfo.quant_precision', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=375,
)


_NODESCALEPAIR = _descriptor.Descriptor(
  name='NodeScalePair',
  full_name='light.NodeScalePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_info', full_name='light.NodeScalePair.node_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_info', full_name='light.NodeScalePair.scale_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_info_list', full_name='light.NodeScalePair.scale_info_list', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='scale_option', full_name='light.NodeScalePair.scale_option',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=378,
  serialized_end=534,
)


_QUANTSCALESDATA = _descriptor.Descriptor(
  name='QuantScalesData',
  full_name='light.QuantScalesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='light.QuantScalesData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=589,
)


_SIMPLEMAP_SIMPLEMAPENTRY = _descriptor.Descriptor(
  name='SimpleMapEntry',
  full_name='light.SimpleMap.SimpleMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='light.SimpleMap.SimpleMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='light.SimpleMap.SimpleMapEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=705,
)

_SIMPLEMAP = _descriptor.Descriptor(
  name='SimpleMap',
  full_name='light.SimpleMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simple_map', full_name='light.SimpleMap.simple_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SIMPLEMAP_SIMPLEMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=705,
)


_SCALEINFOMAP_SCALEINFOMAPENTRY = _descriptor.Descriptor(
  name='ScaleInfoMapEntry',
  full_name='light.ScaleInfoMap.ScaleInfoMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='light.ScaleInfoMap.ScaleInfoMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='light.ScaleInfoMap.ScaleInfoMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=856,
)

_SCALEINFOMAP = _descriptor.Descriptor(
  name='ScaleInfoMap',
  full_name='light.ScaleInfoMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale_info_map', full_name='light.ScaleInfoMap.scale_info_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCALEINFOMAP_SCALEINFOMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=856,
)

_CALIBRATIONHISTOGRAM_VALUETYPE.containing_type = _CALIBRATIONHISTOGRAM
_SCALEINFOLIST.fields_by_name['l'].message_type = _SCALEINFO
_NODESCALEPAIR.fields_by_name['node_info'].message_type = _NODEINFO
_NODESCALEPAIR.fields_by_name['scale_info'].message_type = _SCALEINFO
_NODESCALEPAIR.fields_by_name['scale_info_list'].message_type = _SCALEINFOLIST
_NODESCALEPAIR.oneofs_by_name['scale_option'].fields.append(
  _NODESCALEPAIR.fields_by_name['scale_info'])
_NODESCALEPAIR.fields_by_name['scale_info'].containing_oneof = _NODESCALEPAIR.oneofs_by_name['scale_option']
_NODESCALEPAIR.oneofs_by_name['scale_option'].fields.append(
  _NODESCALEPAIR.fields_by_name['scale_info_list'])
_NODESCALEPAIR.fields_by_name['scale_info_list'].containing_oneof = _NODESCALEPAIR.oneofs_by_name['scale_option']
_QUANTSCALESDATA.fields_by_name['data'].message_type = _NODESCALEPAIR
_SIMPLEMAP_SIMPLEMAPENTRY.containing_type = _SIMPLEMAP
_SIMPLEMAP.fields_by_name['simple_map'].message_type = _SIMPLEMAP_SIMPLEMAPENTRY
_SCALEINFOMAP_SCALEINFOMAPENTRY.fields_by_name['value'].message_type = _SCALEINFO
_SCALEINFOMAP_SCALEINFOMAPENTRY.containing_type = _SCALEINFOMAP
_SCALEINFOMAP.fields_by_name['scale_info_map'].message_type = _SCALEINFOMAP_SCALEINFOMAPENTRY
DESCRIPTOR.message_types_by_name['CalibrationHistogram'] = _CALIBRATIONHISTOGRAM
DESCRIPTOR.message_types_by_name['ScaleInfo'] = _SCALEINFO
DESCRIPTOR.message_types_by_name['ScaleInfoList'] = _SCALEINFOLIST
DESCRIPTOR.message_types_by_name['NodeInfo'] = _NODEINFO
DESCRIPTOR.message_types_by_name['NodeScalePair'] = _NODESCALEPAIR
DESCRIPTOR.message_types_by_name['QuantScalesData'] = _QUANTSCALESDATA
DESCRIPTOR.message_types_by_name['SimpleMap'] = _SIMPLEMAP
DESCRIPTOR.message_types_by_name['ScaleInfoMap'] = _SCALEINFOMAP
DESCRIPTOR.enum_types_by_name['HistogramMode'] = _HISTOGRAMMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibrationHistogram = _reflection.GeneratedProtocolMessageType('CalibrationHistogram', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATIONHISTOGRAM,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.CalibrationHistogram)
  })
_sym_db.RegisterMessage(CalibrationHistogram)

ScaleInfo = _reflection.GeneratedProtocolMessageType('ScaleInfo', (_message.Message,), {
  'DESCRIPTOR' : _SCALEINFO,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.ScaleInfo)
  })
_sym_db.RegisterMessage(ScaleInfo)

ScaleInfoList = _reflection.GeneratedProtocolMessageType('ScaleInfoList', (_message.Message,), {
  'DESCRIPTOR' : _SCALEINFOLIST,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.ScaleInfoList)
  })
_sym_db.RegisterMessage(ScaleInfoList)

NodeInfo = _reflection.GeneratedProtocolMessageType('NodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _NODEINFO,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.NodeInfo)
  })
_sym_db.RegisterMessage(NodeInfo)

NodeScalePair = _reflection.GeneratedProtocolMessageType('NodeScalePair', (_message.Message,), {
  'DESCRIPTOR' : _NODESCALEPAIR,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.NodeScalePair)
  })
_sym_db.RegisterMessage(NodeScalePair)

QuantScalesData = _reflection.GeneratedProtocolMessageType('QuantScalesData', (_message.Message,), {
  'DESCRIPTOR' : _QUANTSCALESDATA,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.QuantScalesData)
  })
_sym_db.RegisterMessage(QuantScalesData)

SimpleMap = _reflection.GeneratedProtocolMessageType('SimpleMap', (_message.Message,), {

  'SimpleMapEntry' : _reflection.GeneratedProtocolMessageType('SimpleMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SIMPLEMAP_SIMPLEMAPENTRY,
    '__module__' : 'sdk2.proto.calibration_pb2'
    # @@protoc_insertion_point(class_scope:light.SimpleMap.SimpleMapEntry)
    })
  ,
  'DESCRIPTOR' : _SIMPLEMAP,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.SimpleMap)
  })
_sym_db.RegisterMessage(SimpleMap)
_sym_db.RegisterMessage(SimpleMap.SimpleMapEntry)

ScaleInfoMap = _reflection.GeneratedProtocolMessageType('ScaleInfoMap', (_message.Message,), {

  'ScaleInfoMapEntry' : _reflection.GeneratedProtocolMessageType('ScaleInfoMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SCALEINFOMAP_SCALEINFOMAPENTRY,
    '__module__' : 'sdk2.proto.calibration_pb2'
    # @@protoc_insertion_point(class_scope:light.ScaleInfoMap.ScaleInfoMapEntry)
    })
  ,
  'DESCRIPTOR' : _SCALEINFOMAP,
  '__module__' : 'sdk2.proto.calibration_pb2'
  # @@protoc_insertion_point(class_scope:light.ScaleInfoMap)
  })
_sym_db.RegisterMessage(ScaleInfoMap)
_sym_db.RegisterMessage(ScaleInfoMap.ScaleInfoMapEntry)


_SIMPLEMAP_SIMPLEMAPENTRY._options = None
_SCALEINFOMAP_SCALEINFOMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
