# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk2/proto/dtypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sdk2/proto/dtypes.proto',
  package='light',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17sdk2/proto/dtypes.proto\x12\x05light\"*\n\x05\x44Type\x12\x16\n\x01t\x18\x01 \x01(\x0e\x32\x0b.light.Type\x12\t\n\x01p\x18\x02 \x01(\x05*\x93\x01\n\x04Type\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\r\n\tDT_BFLOAT\x10\x02\x12\n\n\x06\x44T_INT\x10\x03\x12\x0b\n\x07\x44T_UINT\x10\x04\x12\x0b\n\x07\x44T_QINT\x10\x05\x12\x0c\n\x08\x44T_QUINT\x10\x06\x12\x0e\n\nDT_COMPLEX\x10\x07\x12\x0b\n\x07\x44T_BOOL\x10\x08\x12\r\n\tDT_STRING\x10\tb\x06proto3')
)

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='light.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DT_INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_FLOAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_BFLOAT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_INT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_UINT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_QINT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_QUINT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_COMPLEX', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_BOOL', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DT_STRING', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=79,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
DT_INVALID = 0
DT_FLOAT = 1
DT_BFLOAT = 2
DT_INT = 3
DT_UINT = 4
DT_QINT = 5
DT_QUINT = 6
DT_COMPLEX = 7
DT_BOOL = 8
DT_STRING = 9



_DTYPE = _descriptor.Descriptor(
  name='DType',
  full_name='light.DType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='light.DType.t', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p', full_name='light.DType.p', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=76,
)

_DTYPE.fields_by_name['t'].enum_type = _TYPE
DESCRIPTOR.message_types_by_name['DType'] = _DTYPE
DESCRIPTOR.enum_types_by_name['Type'] = _TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DType = _reflection.GeneratedProtocolMessageType('DType', (_message.Message,), {
  'DESCRIPTOR' : _DTYPE,
  '__module__' : 'sdk2.proto.dtypes_pb2'
  # @@protoc_insertion_point(class_scope:light.DType)
  })
_sym_db.RegisterMessage(DType)


# @@protoc_insertion_point(module_scope)
