# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_sdk/proto/graph_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_sdk/proto/graph_types.proto',
  package='light',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1elt_sdk/proto/graph_types.proto\x12\x05light*\x97\x01\n\tGraphType\x12\x0f\n\x0bLGFProtobuf\x10\x00\x12\x10\n\x0cTFSavedModel\x10\x01\x12\x14\n\x10TFLiteSavedModel\x10\x02\x12\x18\n\x14TFTrainingSavedModel\x10\x03\x12\x18\n\x14TFTrainingCheckpoint\x10\x04\x12\x0e\n\nTFGraphDef\x10\x05\x12\r\n\tONNXModel\x10\x06\x62\x06proto3')
)

_GRAPHTYPE = _descriptor.EnumDescriptor(
  name='GraphType',
  full_name='light.GraphType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LGFProtobuf', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TFSavedModel', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TFLiteSavedModel', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TFTrainingSavedModel', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TFTrainingCheckpoint', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TFGraphDef', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONNXModel', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=42,
  serialized_end=193,
)
_sym_db.RegisterEnumDescriptor(_GRAPHTYPE)

GraphType = enum_type_wrapper.EnumTypeWrapper(_GRAPHTYPE)
LGFProtobuf = 0
TFSavedModel = 1
TFLiteSavedModel = 2
TFTrainingSavedModel = 3
TFTrainingCheckpoint = 4
TFGraphDef = 5
ONNXModel = 6


DESCRIPTOR.enum_types_by_name['GraphType'] = _GRAPHTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
