# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from lt_sdk.proto import inference_pb2 as lt__sdk_dot_proto_dot_inference__pb2


class LTInferenceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetInputSpec = channel.unary_unary(
        '/light.LTInference/GetInputSpec',
        request_serializer=lt__sdk_dot_proto_dot_inference__pb2.GetInputSpecRequest.SerializeToString,
        response_deserializer=lt__sdk_dot_proto_dot_inference__pb2.GetInputSpecResponse.FromString,
        )
    self.Predict = channel.unary_unary(
        '/light.LTInference/Predict',
        request_serializer=lt__sdk_dot_proto_dot_inference__pb2.BatchedInferenceInput.SerializeToString,
        response_deserializer=lt__sdk_dot_proto_dot_inference__pb2.BatchedInferenceOutput.FromString,
        )
    self.PredictBatch = channel.unary_unary(
        '/light.LTInference/PredictBatch',
        request_serializer=lt__sdk_dot_proto_dot_inference__pb2.InferenceInput.SerializeToString,
        response_deserializer=lt__sdk_dot_proto_dot_inference__pb2.InferenceOutput.FromString,
        )


class LTInferenceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetInputSpec(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Predict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PredictBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LTInferenceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetInputSpec': grpc.unary_unary_rpc_method_handler(
          servicer.GetInputSpec,
          request_deserializer=lt__sdk_dot_proto_dot_inference__pb2.GetInputSpecRequest.FromString,
          response_serializer=lt__sdk_dot_proto_dot_inference__pb2.GetInputSpecResponse.SerializeToString,
      ),
      'Predict': grpc.unary_unary_rpc_method_handler(
          servicer.Predict,
          request_deserializer=lt__sdk_dot_proto_dot_inference__pb2.BatchedInferenceInput.FromString,
          response_serializer=lt__sdk_dot_proto_dot_inference__pb2.BatchedInferenceOutput.SerializeToString,
      ),
      'PredictBatch': grpc.unary_unary_rpc_method_handler(
          servicer.PredictBatch,
          request_deserializer=lt__sdk_dot_proto_dot_inference__pb2.InferenceInput.FromString,
          response_serializer=lt__sdk_dot_proto_dot_inference__pb2.InferenceOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'light.LTInference', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
