# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_sdk/proto/memory_layout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lt_sdk.proto import subgraph_binary_pb2 as lt__sdk_dot_proto_dot_subgraph__binary__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_sdk/proto/memory_layout.proto',
  package='light',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n lt_sdk/proto/memory_layout.proto\x12\x05light\x1a\"lt_sdk/proto/subgraph_binary.proto\"9\n\x0eMemorySnapshot\x12\'\n\x06\x61llocs\x18\x01 \x03(\x0b\x32\x17.light.MemoryAllocation\"b\n\x0cMemoryLayout\x12\x11\n\tnum_banks\x18\x01 \x01(\x05\x12\x15\n\rrows_per_bank\x18\x02 \x01(\x05\x12(\n\tsnapshots\x18\x03 \x03(\x0b\x32\x15.light.MemorySnapshot\"\xa8\x01\n\x10\x46ullMemoryLayout\x12G\n\x11memory_layout_map\x18\x01 \x03(\x0b\x32,.light.FullMemoryLayout.MemoryLayoutMapEntry\x1aK\n\x14MemoryLayoutMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.light.MemoryLayout:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[lt__sdk_dot_proto_dot_subgraph__binary__pb2.DESCRIPTOR,])




_MEMORYSNAPSHOT = _descriptor.Descriptor(
  name='MemorySnapshot',
  full_name='light.MemorySnapshot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allocs', full_name='light.MemorySnapshot.allocs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=136,
)


_MEMORYLAYOUT = _descriptor.Descriptor(
  name='MemoryLayout',
  full_name='light.MemoryLayout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_banks', full_name='light.MemoryLayout.num_banks', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows_per_bank', full_name='light.MemoryLayout.rows_per_bank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='snapshots', full_name='light.MemoryLayout.snapshots', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=236,
)


_FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY = _descriptor.Descriptor(
  name='MemoryLayoutMapEntry',
  full_name='light.FullMemoryLayout.MemoryLayoutMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='light.FullMemoryLayout.MemoryLayoutMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='light.FullMemoryLayout.MemoryLayoutMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=407,
)

_FULLMEMORYLAYOUT = _descriptor.Descriptor(
  name='FullMemoryLayout',
  full_name='light.FullMemoryLayout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='memory_layout_map', full_name='light.FullMemoryLayout.memory_layout_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=407,
)

_MEMORYSNAPSHOT.fields_by_name['allocs'].message_type = lt__sdk_dot_proto_dot_subgraph__binary__pb2._MEMORYALLOCATION
_MEMORYLAYOUT.fields_by_name['snapshots'].message_type = _MEMORYSNAPSHOT
_FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY.fields_by_name['value'].message_type = _MEMORYLAYOUT
_FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY.containing_type = _FULLMEMORYLAYOUT
_FULLMEMORYLAYOUT.fields_by_name['memory_layout_map'].message_type = _FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY
DESCRIPTOR.message_types_by_name['MemorySnapshot'] = _MEMORYSNAPSHOT
DESCRIPTOR.message_types_by_name['MemoryLayout'] = _MEMORYLAYOUT
DESCRIPTOR.message_types_by_name['FullMemoryLayout'] = _FULLMEMORYLAYOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemorySnapshot = _reflection.GeneratedProtocolMessageType('MemorySnapshot', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYSNAPSHOT,
  '__module__' : 'lt_sdk.proto.memory_layout_pb2'
  # @@protoc_insertion_point(class_scope:light.MemorySnapshot)
  })
_sym_db.RegisterMessage(MemorySnapshot)

MemoryLayout = _reflection.GeneratedProtocolMessageType('MemoryLayout', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYLAYOUT,
  '__module__' : 'lt_sdk.proto.memory_layout_pb2'
  # @@protoc_insertion_point(class_scope:light.MemoryLayout)
  })
_sym_db.RegisterMessage(MemoryLayout)

FullMemoryLayout = _reflection.GeneratedProtocolMessageType('FullMemoryLayout', (_message.Message,), {

  'MemoryLayoutMapEntry' : _reflection.GeneratedProtocolMessageType('MemoryLayoutMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY,
    '__module__' : 'lt_sdk.proto.memory_layout_pb2'
    # @@protoc_insertion_point(class_scope:light.FullMemoryLayout.MemoryLayoutMapEntry)
    })
  ,
  'DESCRIPTOR' : _FULLMEMORYLAYOUT,
  '__module__' : 'lt_sdk.proto.memory_layout_pb2'
  # @@protoc_insertion_point(class_scope:light.FullMemoryLayout)
  })
_sym_db.RegisterMessage(FullMemoryLayout)
_sym_db.RegisterMessage(FullMemoryLayout.MemoryLayoutMapEntry)


_FULLMEMORYLAYOUT_MEMORYLAYOUTMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
