# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lt_sdk/proto/ops.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lt_sdk/proto/ops.proto',
  package='light',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16lt_sdk/proto/ops.proto\x12\x05light*\xc8\x04\n\x02Op\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07RESHAPE\x10\x01\x12\t\n\x05\x43ONST\x10\x02\x12\x08\n\x04\x43\x41ST\x10\x03\x12\n\n\x06MATMUL\x10\x04\x12\n\n\x06\x43ONV2D\x10\x05\x12\x14\n\x10\x44\x45PTHWISE_CONV2D\x10\x15\x12\x0b\n\x07MAXPOOL\x10\x06\x12\x0b\n\x07\x41VGPOOL\x10\x1a\x12\r\n\tBATCHNORM\x10\x07\x12\x07\n\x03PAD\x10\x08\x12\x08\n\x04MEAN\x10\t\x12\x0b\n\x07SOFTMAX\x10\n\x12\x0b\n\x07SQUEEZE\x10\x1b\x12\x07\n\x03\x41\x44\x44\x10\x0b\x12\x08\n\x04RELU\x10\x0c\x12\t\n\x05RELU6\x10\x14\x12\x13\n\x0f\x46ULLY_CONNECTED\x10\r\x12\x0c\n\x08VARIABLE\x10\x16\x12\n\n\x06\x41SSIGN\x10\x19\x12\t\n\x05SWISH\x10\x1c\x12\x0c\n\x08MULTIPLY\x10\x1d\x12\x0b\n\x07SIGMOID\x10\x1e\x12\r\n\tTRANSPOSE\x10\x1f\x12\x08\n\x04TANH\x10 \x12\x0b\n\x07UNSTACK\x10!\x12\x07\n\x03SUB\x10\"\x12\x07\n\x03POW\x10#\x12\x0e\n\nEXPANDDIMS\x10$\x12\x08\n\x04\x46ILL\x10%\x12\t\n\x05RSQRT\x10&\x12\x16\n\x12SQUARED_DIFFERENCE\x10\'\x12\t\n\x05STACK\x10(\x12\x0f\n\x0b\x42\x41TCHMATMUL\x10)\x12\x08\n\x04TILE\x10*\x12\n\n\x06\x43ONCAT\x10+\x12\t\n\x05SPLIT\x10,\x12\x0c\n\x08IDENTITY\x10\x0e\x12\t\n\x05\x45NTER\x10\x0f\x12\n\n\x06SWITCH\x10\x10\x12\t\n\x05MERGE\x10\x11\x12\x12\n\x0eNEXT_ITERATION\x10\x12\x12\x08\n\x04\x45XIT\x10\x13\x12\x0c\n\x08QUANTIZE\x10\x17\x12\x0e\n\nDEQUANTIZE\x10\x18\x62\x06proto3')
)

_OP = _descriptor.EnumDescriptor(
  name='Op',
  full_name='light.Op',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESHAPE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAST', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MATMUL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONV2D', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEPTHWISE_CONV2D', index=6, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXPOOL', index=7, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVGPOOL', index=8, number=26,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATCHNORM', index=9, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAD', index=10, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEAN', index=11, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTMAX', index=12, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQUEEZE', index=13, number=27,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=14, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU', index=15, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU6', index=16, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULLY_CONNECTED', index=17, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VARIABLE', index=18, number=22,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASSIGN', index=19, number=25,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWISH', index=20, number=28,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLY', index=21, number=29,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGMOID', index=22, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSPOSE', index=23, number=31,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANH', index=24, number=32,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSTACK', index=25, number=33,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUB', index=26, number=34,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POW', index=27, number=35,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPANDDIMS', index=28, number=36,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILL', index=29, number=37,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RSQRT', index=30, number=38,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQUARED_DIFFERENCE', index=31, number=39,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STACK', index=32, number=40,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATCHMATMUL', index=33, number=41,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TILE', index=34, number=42,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONCAT', index=35, number=43,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPLIT', index=36, number=44,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDENTITY', index=37, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER', index=38, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWITCH', index=39, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MERGE', index=40, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEXT_ITERATION', index=41, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=42, number=19,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUANTIZE', index=43, number=23,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEQUANTIZE', index=44, number=24,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=34,
  serialized_end=618,
)
_sym_db.RegisterEnumDescriptor(_OP)

Op = enum_type_wrapper.EnumTypeWrapper(_OP)
UNKNOWN = 0
RESHAPE = 1
CONST = 2
CAST = 3
MATMUL = 4
CONV2D = 5
DEPTHWISE_CONV2D = 21
MAXPOOL = 6
AVGPOOL = 26
BATCHNORM = 7
PAD = 8
MEAN = 9
SOFTMAX = 10
SQUEEZE = 27
ADD = 11
RELU = 12
RELU6 = 20
FULLY_CONNECTED = 13
VARIABLE = 22
ASSIGN = 25
SWISH = 28
MULTIPLY = 29
SIGMOID = 30
TRANSPOSE = 31
TANH = 32
UNSTACK = 33
SUB = 34
POW = 35
EXPANDDIMS = 36
FILL = 37
RSQRT = 38
SQUARED_DIFFERENCE = 39
STACK = 40
BATCHMATMUL = 41
TILE = 42
CONCAT = 43
SPLIT = 44
IDENTITY = 14
ENTER = 15
SWITCH = 16
MERGE = 17
NEXT_ITERATION = 18
EXIT = 19
QUANTIZE = 23
DEQUANTIZE = 24


DESCRIPTOR.enum_types_by_name['Op'] = _OP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
